language: node_js

node_js: stable

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - git config --global user.name "micooz"
  - git config --global user.email "micooz@hotmail.com"
  - git submodule update --init --recursive
  - sed -i "s/git@github.com:/https:\/\/${GITHUB_TOKEN}@github.com\//" _config.yml

script:
  - hexo clean
  - hexo generate
  - hexo deploy
