language: node_js

node_js: stable

branches:
  only:
    - master

install:
  - yarn

before_script:
  - git submodule update --init --recursive

script:
  - hexo clean
  - hexo generate

after_script:
  - hexo deploy

cache:
  yarn: true
  directories:
    - node_modules
